require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
rn_maps_path = '../node_modules/react-native-maps'

platform :ios, '10.0'

target 'TrollyMart' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  pod 'Firebase/Auth'

  pod 'Firebase/Firestore'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'Permission-LocationAccuracy', :path => "../node_modules/react-native-permissions/ios/LocationAccuracy"

  pod 'Permission-LocationAlways', :path => "../node_modules/react-native-permissions/ios/LocationAlways"

  pod 'Permission-LocationWhenInUse', :path => "../node_modules/react-native-permissions/ios/LocationWhenInUse"

  pod 'react-native-google-maps', :path => rn_maps_path 

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'TrollyMartTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  post_install do |installer|
    react_native_post_install(installer)
  end
end